version: "3"

services:
  neo4j-visjs:
    build:
      context: .
    ports:
      - 8080:8080
    env_file: .env
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:4.1.0
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
    environment:
      - NEO4J_AUTH=neo4j/test
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./internal/sample:/usr/share/nginx/html:ro
